# 01 — Data Collection: Pollen & Weather Data for France

**Objective:** Fetch daily pollen concentrations and meteorological covariates for 4 French cities (2022–2024) from the Open-Meteo APIs.

**Cities:**
| City | Climate | Latitude | Longitude |
|------|---------|----------|-----------|
| Paris | Oceanic / Continental | 48.8566 | 2.3522 |
| Marseille | Mediterranean | 43.2965 | 5.3698 |
| Strasbourg | Continental | 48.5734 | 7.7521 |
| Bordeaux | Oceanic | 44.8378 | −0.5792 |

**Data sources:**
- **Pollen:** Open-Meteo Air Quality API (CAMS / Copernicus) — hourly → resampled to daily mean
- **Weather:** Open-Meteo Historical Weather API (ERA5) — already daily

In [1]:
# ── Imports ──────────────────────────────────────────────────────────────────
import os
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import openmeteo_requests
import requests_cache
from retry_requests import retry

warnings.filterwarnings("ignore")
np.random.seed(42)

# ── Unified Style ────────────────────────────────────────────────────────────
plt.rcParams.update({
    # Figure
    "figure.dpi": 120,
    "figure.facecolor": "white",
    "savefig.dpi": 200,
    "savefig.bbox": "tight",
    # Fonts
    "font.family": "sans-serif",
    "font.size": 11,
    "axes.titlesize": 13,
    "axes.titleweight": "bold",
    "axes.labelsize": 11,
    # Grid
    "axes.grid": True,
    "grid.alpha": 0.3,
    "grid.linewidth": 0.6,
    # Spines
    "axes.spines.top": False,
    "axes.spines.right": False,
    # Legend
    "legend.framealpha": 0.9,
    "legend.edgecolor": "0.8",
    "legend.fontsize": 9,
})

# ── Unified Colour Palette ───────────────────────────────────────────────────
CITY_COLORS = {
    "Paris": "#4C72B0", "Marseille": "#DD8452",
    "Strasbourg": "#55A868", "Bordeaux": "#C44E52",
}
SPECIES_COLORS = {
    "grass_pollen": "#55A868", "birch_pollen": "#8C564B",
    "olive_pollen": "#E5AE38", "alder_pollen": "#64B5CD",
    "mugwort_pollen": "#8172B3", "ragweed_pollen": "#DA8BC3",
}
YEAR_COLORS = {2022: "#4C72B0", 2023: "#DD8452", 2024: "#55A868"}

# ── Paths ────────────────────────────────────────────────────────────────────
DATA_RAW = os.path.join("..", "Data", "raw")
DATA_PROC = os.path.join("..", "Data", "processed")
FIG_DIR = os.path.join("..", "figures")
os.makedirs(DATA_RAW, exist_ok=True)
os.makedirs(DATA_PROC, exist_ok=True)
os.makedirs(FIG_DIR, exist_ok=True)

print("Setup complete.")

Setup complete.

In [2]:
# ── Configuration ────────────────────────────────────────────────────────────
CITIES = {
    "Paris":      {"lat": 48.8566, "lon": 2.3522,  "climate": "Oceanic/Continental"},
    "Marseille":  {"lat": 43.2965, "lon": 5.3698,  "climate": "Mediterranean"},
    "Strasbourg": {"lat": 48.5734, "lon": 7.7521,  "climate": "Continental"},
    "Bordeaux":   {"lat": 44.8378, "lon": -0.5792, "climate": "Oceanic"},
}

START_DATE = "2022-01-01"
END_DATE   = "2024-12-31"

POLLEN_SPECIES = [
    "birch_pollen", "alder_pollen", "grass_pollen",
    "olive_pollen", "mugwort_pollen", "ragweed_pollen",
]

WEATHER_VARS = [
    # Core variables (original)
    "temperature_2m_mean", "temperature_2m_max", "temperature_2m_min",
    "precipitation_sum", "windspeed_10m_max", "sunshine_duration",
    "relative_humidity_2m_mean",
    # New variables (added for enriched modelling)
    "surface_pressure_mean",          # hPa — thermal inversions trap pollen near ground
    "shortwave_radiation_sum",        # MJ/m² — UV proxy, triggers pollen release in grasses
    "winddirection_10m_dominant",     # degrees — long-range pollen transport direction
]

AQ_VARS = [
    "ozone",              # µg/m³ — O3: photo-oxidant, degrades pollen protein coat → amplifies allergenicity
    "nitrogen_dioxide",   # µg/m³ — NO2: urban traffic marker, co-exposure enhancer
    "pm2_5",              # µg/m³ — fine particles: pollen fragment carrier, synergistic irritant
]

print(f"Cities: {list(CITIES.keys())}")
print(f"Period: {START_DATE} → {END_DATE}")
print(f"Pollen species: {len(POLLEN_SPECIES)}, Weather variables: {len(WEATHER_VARS)}, AQ variables: {len(AQ_VARS)}")

Cities: ['Paris', 'Marseille', 'Strasbourg', 'Bordeaux']
Period: 2022-01-01 → 2024-12-31
Pollen species: 6, Weather variables: 10, AQ variables: 3

In [3]:
# ── Open-Meteo client with caching & retry ──────────────────────────────────
cache_session = requests_cache.CachedSession(
    os.path.join(DATA_RAW, ".cache"), expire_after=3600
)
retry_session = retry(cache_session, retries=5, backoff_factor=0.2)
om = openmeteo_requests.Client(session=retry_session)

print("Open-Meteo client ready (cached + retry).")

Open-Meteo client ready (cached + retry).

## 1 — Pollen Data (Air Quality API)

The Open-Meteo Air Quality API provides **hourly** pollen concentrations (grains/m³) from the CAMS European model.  
We fetch hourly data per city, then resample to **daily mean** to align with weather data.

In [4]:
# ── Fetch hourly pollen data for all cities ──────────────────────────────────
def fetch_pollen(city_name, lat, lon):
    """Fetch hourly pollen data from Open-Meteo Air Quality API and resample to daily mean."""
    url = "https://air-quality-api.open-meteo.com/v1/air-quality"
    params = {
        "latitude": lat,
        "longitude": lon,
        "hourly": POLLEN_SPECIES,
        "start_date": START_DATE,
        "end_date": END_DATE,
        "timezone": "Europe/Paris",
    }
    responses = om.weather_api(url, params=params)
    response = responses[0]

    # Build hourly DataFrame
    hourly = response.Hourly()
    hourly_data = {
        "datetime": pd.date_range(
            start=pd.to_datetime(hourly.Time(), unit="s", utc=True),
            end=pd.to_datetime(hourly.TimeEnd(), unit="s", utc=True),
            freq=pd.Timedelta(seconds=hourly.Interval()),
            inclusive="left",
        )
    }
    for i, species in enumerate(POLLEN_SPECIES):
        hourly_data[species] = hourly.Variables(i).ValuesAsNumpy()

    df = pd.DataFrame(hourly_data)
    df["datetime"] = df["datetime"].dt.tz_convert("Europe/Paris")

    # Resample to daily mean
    df = df.set_index("datetime").resample("D").mean()
    df.index = df.index.date
    df.index.name = "date"
    df["city"] = city_name

    return df

# Fetch all cities
pollen_frames = []
for city, info in CITIES.items():
    print(f"Fetching pollen for {city}...")
    df = fetch_pollen(city, info["lat"], info["lon"])
    pollen_frames.append(df)
    print(f"  → {len(df)} days, {df.shape[1]-1} species")

pollen_raw = pd.concat(pollen_frames).reset_index()
pollen_raw["date"] = pd.to_datetime(pollen_raw["date"])
print(f"\nTotal pollen records: {len(pollen_raw)}")
pollen_raw.head()

Fetching pollen for Paris...

  → 1097 days, 6 species
Fetching pollen for Marseille...

  → 1097 days, 6 species
Fetching pollen for Strasbourg...

  → 1097 days, 6 species
Fetching pollen for Bordeaux...

  → 1097 days, 6 species

Total pollen records: 4388

,date,birch_pollen,alder_pollen,grass_pollen,olive_pollen,mugwort_pollen,ragweed_pollen,city
0,2021-12-31,NaN,NaN,NaN,NaN,NaN,NaN,Paris
1,2022-01-01,NaN,0.0,NaN,0.0,NaN,NaN,Paris
2,2022-01-02,NaN,0.0,NaN,0.0,NaN,NaN,Paris
3,2022-01-03,NaN,0.0,NaN,0.0,NaN,NaN,Paris
4,2022-01-04,NaN,0.0,NaN,0.0,NaN,NaN,Paris

### 1b — Air Quality Data (O3, NO₂, PM₂.₅)

Same Open-Meteo Air Quality API endpoint. Three pollutants fetched at **hourly** resolution and resampled to **daily mean** — same pipeline as pollen.

| Variable | Unit | Role in HPI |
|:---|:---|:---|
| `ozone` | µg/m³ | Photo-oxidant: degrades pollen protein coat, amplifies IgE response |
| `nitrogen_dioxide` | µg/m³ | Urban co-exposure proxy, increases airway permeability |
| `pm2_5` | µg/m³ | Fine particle carrier for pollen sub-fragments |

In [5]:
# ── Fetch hourly air quality data for all cities ──────────────────────────────
def fetch_air_quality(city_name, lat, lon):
    """Fetch hourly O3/NO2/PM2.5 from Open-Meteo AQ API and resample to daily mean."""
    url = "https://air-quality-api.open-meteo.com/v1/air-quality"
    params = {
        "latitude": lat,
        "longitude": lon,
        "hourly": AQ_VARS,
        "start_date": START_DATE,
        "end_date": END_DATE,
        "timezone": "Europe/Paris",
    }
    responses = om.weather_api(url, params=params)
    response = responses[0]

    hourly = response.Hourly()
    hourly_data = {
        "datetime": pd.date_range(
            start=pd.to_datetime(hourly.Time(), unit="s", utc=True),
            end=pd.to_datetime(hourly.TimeEnd(), unit="s", utc=True),
            freq=pd.Timedelta(seconds=hourly.Interval()),
            inclusive="left",
        )
    }
    for i, var in enumerate(AQ_VARS):
        hourly_data[var] = hourly.Variables(i).ValuesAsNumpy()

    df = pd.DataFrame(hourly_data)
    df["datetime"] = df["datetime"].dt.tz_convert("Europe/Paris")

    df = df.set_index("datetime").resample("D").mean()
    df.index = df.index.date
    df.index.name = "date"
    df["city"] = city_name
    return df

# Fetch all cities
aq_frames = []
for city, info in CITIES.items():
    print(f"Fetching air quality for {city}...")
    df = fetch_air_quality(city, info["lat"], info["lon"])
    aq_frames.append(df)
    print(f"  → {len(df)} days, {df.shape[1]-1} variables")

aq_raw = pd.concat(aq_frames).reset_index()
aq_raw["date"] = pd.to_datetime(aq_raw["date"])
print(f"\nTotal AQ records: {len(aq_raw)}")
aq_raw.head()

Fetching air quality for Paris...

  → 1097 days, 3 variables
Fetching air quality for Marseille...

  → 1097 days, 3 variables
Fetching air quality for Strasbourg...

  → 1097 days, 3 variables
Fetching air quality for Bordeaux...

  → 1097 days, 3 variables

Total AQ records: 4388

        date      ozone  nitrogen_dioxide      pm2_5   city
0 2021-12-31  19.000000         23.299999  14.000000  Paris
1 2022-01-01   9.958333         29.400000  14.854167  Paris
2 2022-01-02  36.750000         18.283333   9.441667  Paris
3 2022-01-03  55.541668         15.633334   7.791667  Paris
4 2022-01-04  47.875000         22.616667   5.283333  Paris

## 2 — Weather Data (Historical Weather API)

ERA5 reanalysis data at daily resolution. **10 variables** spanning the main meteorological drivers of pollen dynamics:

| Variable | Unit | Rationale |
|:---|:---|:---|
| `temperature_2m_mean/max/min` | °C | Primary phenological driver (GDD, season onset) |
| `precipitation_sum` | mm | Rain washes pollen out of the air |
| `windspeed_10m_max` | km/h | Dispersal intensity |
| `sunshine_duration` | s → h | UV exposure triggers anther opening |
| `relative_humidity_2m_mean` | % | High humidity weighs down grains, reducing airborne concentration |
| `surface_pressure_mean` | hPa |  thermal inversions (high pressure) trap pollen near ground |
| `shortwave_radiation_sum` | MJ/m² | UV radiation proxy, triggers pollen release in grasses |
| `winddirection_10m_dominant` | ° | long-range pollen transport (esp. ragweed from Eastern Europe) |

In [6]:
# ── Fetch daily weather data for all cities ──────────────────────────────────
def fetch_weather(city_name, lat, lon):
    """Fetch daily weather data from Open-Meteo Historical Weather API."""
    url = "https://archive-api.open-meteo.com/v1/archive"
    params = {
        "latitude": lat,
        "longitude": lon,
        "daily": WEATHER_VARS,
        "start_date": START_DATE,
        "end_date": END_DATE,
        "timezone": "Europe/Paris",
    }
    responses = om.weather_api(url, params=params)
    response = responses[0]

    daily = response.Daily()
    daily_values = {
        var: daily.Variables(i).ValuesAsNumpy()
        for i, var in enumerate(WEATHER_VARS)
    }

    expected_dates = pd.date_range(START_DATE, END_DATE, freq="D")
    n_returned_days = len(next(iter(daily_values.values())))
    assert n_returned_days == len(expected_dates), (
        f"{city_name}: Open-Meteo returned {n_returned_days} daily rows, "
        f"expected {len(expected_dates)} for {START_DATE}..{END_DATE}"
    )

    # The daily endpoint already represents local calendar days. Rebuilding the
    # date index from the requested window avoids DST timestamp duplicates.
    df = pd.DataFrame({"date": expected_dates, **daily_values})
    df["city"] = city_name

    return df

# Fetch all cities
weather_frames = []
for city, info in CITIES.items():
    print(f"Fetching weather for {city}...")
    df = fetch_weather(city, info["lat"], info["lon"])
    weather_frames.append(df)
    print(f"  → {len(df)} days, {df.shape[1]-2} variables")

weather_raw = pd.concat(weather_frames, ignore_index=True)
print(f"\nTotal weather records: {len(weather_raw)}")
weather_raw.head()

Fetching weather for Paris...

  → 1096 days, 10 variables
Fetching weather for Marseille...

  → 1096 days, 10 variables
Fetching weather for Strasbourg...

  → 1096 days, 10 variables
Fetching weather for Bordeaux...

  → 1096 days, 10 variables

Total weather records: 4384

,date,temperature_2m_mean,temperature_2m_max,temperature_2m_min,precipitation_sum,windspeed_10m_max,sunshine_duration,relative_humidity_2m_mean,surface_pressure_mean,shortwave_radiation_sum,winddirection_10m_dominant,city
0,2022-01-01,9.118752,13.107528,6.711191,0.000000,15.790833,28245.619141,91.261932,1019.898254,4.64,167.045471,Paris
1,2022-01-02,11.558333,13.868569,8.529487,1.200000,27.076691,20901.398438,79.086143,1014.318848,3.77,222.219376,Paris
2,2022-01-03,11.047916,12.050569,9.981383,5.000000,30.319178,0.000000,85.638336,1011.245300,1.36,224.004242,Paris
3,2022-01-04,8.916666,11.218518,4.300000,20.400003,27.748037,0.000000,89.308105,997.318604,1.27,253.383911,Paris
4,2022-01-05,3.147917,6.157510,0.450000,0.000000,21.945240,28800.000000,79.394226,1009.037659,4.94,285.630005,Paris

## 3 — Save Raw Data

In [7]:
# ── Save raw CSVs ───────────────────────────────────────────────────────────
pollen_raw.to_csv(os.path.join(DATA_RAW, "pollen_raw.csv"), index=False)
weather_raw.to_csv(os.path.join(DATA_RAW, "weather_raw.csv"), index=False)
aq_raw.to_csv(os.path.join(DATA_RAW, "aq_raw.csv"), index=False)
print("Raw data saved:")
print(f"  pollen_raw  : {pollen_raw.shape}")
print(f"  weather_raw : {weather_raw.shape}")
print(f"  aq_raw      : {aq_raw.shape}")

Raw data saved:
  pollen_raw  : (4388, 8)
  weather_raw : (4384, 12)
  aq_raw      : (4388, 5)

## 4 — Data Quality Check

Quick sanity checks before merging:
- Date range coverage and expected daily granularity
- Exact city-name alignment across pollen, weather and AQ
- Missing values per city/variable
- Basic statistics

In [8]:
# ── Date range, granularity and city-name checks ────────────────────────────
expected_dates = pd.date_range(START_DATE, END_DATE, freq="D")
expected_cities = set(CITIES.keys())

for name, frame, value_cols in [
    ("Pollen", pollen_raw, POLLEN_SPECIES),
    ("Weather", weather_raw, WEATHER_VARS),
    ("AQ", aq_raw, AQ_VARS),
]:
    print(f"=== {name} ===")
    print(f"Columns: {frame.columns.tolist()}")
    print(f"Raw date range: {frame['date'].min().date()} → {frame['date'].max().date()}")

    window_frame = frame[(frame["date"] >= START_DATE) & (frame["date"] <= END_DATE)].copy()
    mismatch = sorted(set(window_frame["city"].unique()).symmetric_difference(expected_cities))
    duplicates = window_frame.duplicated(["date", "city"]).sum()
    print(f"City-name mismatch vs project CITIES: {mismatch or 'none'}")
    print(f"Duplicate (date, city) keys in analysis window: {duplicates}")

    coverage = (
        window_frame.groupby("city")
        .agg(start=("date", "min"), end=("date", "max"), n_days=("date", "nunique"))
        .assign(complete_daily=lambda x: x["n_days"].eq(len(expected_dates)))
    )
    display(coverage)
    assert not mismatch, f"{name}: city names must exactly match CITIES"
    assert duplicates == 0, f"{name}: duplicated (date, city) rows"
    assert coverage["complete_daily"].all(), f"{name}: missing city-days in {START_DATE}..{END_DATE}"
    print()

=== Pollen ===
Columns: ['date', 'birch_pollen', 'alder_pollen', 'grass_pollen', 'olive_pollen', 'mugwort_pollen', 'ragweed_pollen', 'city']
Raw date range: 2021-12-31 → 2024-12-31
City-name mismatch vs project CITIES: none
Duplicate (date, city) keys in analysis window: 0

                start        end  n_days  complete_daily
city
Bordeaux   2022-01-01 2024-12-31    1096            True
Marseille  2022-01-01 2024-12-31    1096            True
Paris      2022-01-01 2024-12-31    1096            True
Strasbourg 2022-01-01 2024-12-31    1096            True

=== Weather ===
Columns: ['date', 'temperature_2m_mean', 'temperature_2m_max', 'temperature_2m_min', 'precipitation_sum', 'windspeed_10m_max', 'sunshine_duration', 'relative_humidity_2m_mean', 'surface_pressure_mean', 'shortwave_radiation_sum', 'winddirection_10m_dominant', 'city']
Raw date range: 2022-01-01 → 2024-12-31
City-name mismatch vs project CITIES: none
Duplicate (date, city) keys in analysis window: 0

                start        end  n_days  complete_daily
city
Bordeaux   2022-01-01 2024-12-31    1096            True
Marseille  2022-01-01 2024-12-31    1096            True
Paris      2022-01-01 2024-12-31    1096            True
Strasbourg 2022-01-01 2024-12-31    1096            True

=== AQ ===
Columns: ['date', 'ozone', 'nitrogen_dioxide', 'pm2_5', 'city']
Raw date range: 2021-12-31 → 2024-12-31
City-name mismatch vs project CITIES: none
Duplicate (date, city) keys in analysis window: 0

                start        end  n_days  complete_daily
city
Bordeaux   2022-01-01 2024-12-31    1096            True
Marseille  2022-01-01 2024-12-31    1096            True
Paris      2022-01-01 2024-12-31    1096            True
Strasbourg 2022-01-01 2024-12-31    1096            True

In [9]:
# ── Missing values ──────────────────────────────────────────────────────────
print("=== Pollen — Missing values per city ===")
print(pollen_raw.groupby("city")[POLLEN_SPECIES].apply(lambda x: x.isna().sum()))
print()
print("=== Weather — Missing values per city ===")
print(weather_raw.groupby("city")[WEATHER_VARS].apply(lambda x: x.isna().sum()))
print()
print("=== Air Quality — Missing values per city ===")
print(aq_raw.groupby("city")[AQ_VARS].apply(lambda x: x.isna().sum()))

=== Pollen — Missing values per city ===
            birch_pollen  alder_pollen  grass_pollen  olive_pollen  \
city
Bordeaux             379           323           317           323
Marseille            379           323           317           323
Paris                379           323           317           323
Strasbourg           379           323           317           323

            mugwort_pollen  ragweed_pollen
city
Bordeaux               379             379
Marseille              379             379
Paris                  379             379
Strasbourg             379             379

=== Weather — Missing values per city ===
            temperature_2m_mean  temperature_2m_max  temperature_2m_min  \
city
Bordeaux                      0                   0                   0
Marseille                     0                   0                   0
Paris                         0                   0                   0
Strasbourg                    0                   0                   0

            precipitation_sum  windspeed_10m_max  sunshine_duration  \
city
Bordeaux                    0                  0                  0
Marseille                   0                  0                  0
Paris                       0                  0                  0
Strasbourg                  0                  0                  0

            relative_humidity_2m_mean  surface_pressure_mean  \
city
Bordeaux                            0                      0
Marseille                           0                      0
Paris                               0                      0
Strasbourg                          0                      0

            shortwave_radiation_sum  winddirection_10m_dominant
city
Bordeaux                          0                           0
Marseille                         0                           0
Paris                             0                           0
Strasbourg                        0                           0

=== Air Quality — Missing values per city ===
            ozone  nitrogen_dioxide  pm2_5
city
Bordeaux        0                 0      0
Marseille       0                 0      0
Paris           0                 0      0
Strasbourg      0                 0      0

In [10]:
# ── Basic descriptive stats ─────────────────────────────────────────────────
print("=== Pollen — Summary ===")
display(pollen_raw[POLLEN_SPECIES].describe().round(2))
print()
print("=== Weather — Summary ===")
display(weather_raw[WEATHER_VARS].describe().round(2))
print()
print("=== Air Quality — Summary ===")
display(aq_raw[AQ_VARS].describe().round(2))

=== Pollen — Summary ===

,birch_pollen,alder_pollen,grass_pollen,olive_pollen,mugwort_pollen,ragweed_pollen
count,2872.00,3096.00,3120.00,3096.00,2872.00,2872.00
mean,3.96,0.39,5.81,0.13,2.01,0.34
std,16.47,2.43,11.28,0.88,5.20,1.38
min,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.00,0.00,0.00,0.00,0.00,0.00
50%,0.00,0.00,0.95,0.00,0.03,0.00
75%,0.17,0.03,5.29,0.00,1.42,0.00
max,252.58,81.95,83.06,17.69,63.64,19.75

=== Weather — Summary ===

,temperature_2m_mean,temperature_2m_max,temperature_2m_min,precipitation_sum,windspeed_10m_max,sunshine_duration,relative_humidity_2m_mean,surface_pressure_mean,shortwave_radiation_sum,winddirection_10m_dominant
count,4384.00,4384.00,4384.00,4384.00,4384.00,4384.00,4384.00,4384.00,4384.00,4384.00
mean,13.92,18.19,9.88,2.46,19.49,31255.96,75.03,1011.05,13.70,199.50
std,6.77,7.53,6.28,5.21,8.27,15972.61,11.71,10.47,8.20,102.17
min,-7.75,-3.65,-11.06,0.00,4.50,0.00,33.00,967.51,0.47,0.00
25%,9.12,12.55,5.49,0.00,13.25,20818.44,68.44,1004.23,6.38,122.29
50%,13.71,17.89,9.95,0.10,18.01,33522.56,76.63,1012.46,12.85,212.18
75%,19.35,24.05,14.71,2.40,23.90,44421.30,83.70,1017.88,20.75,288.52
max,30.51,40.61,24.13,64.90,56.62,57058.42,97.91,1038.77,30.04,360.00

=== Air Quality — Summary ===

         ozone  nitrogen_dioxide    pm2_5
count  4388.00           4388.00  4388.00
mean     56.11             14.68     9.82
std      20.87              9.52     6.09
min       1.75              1.79     2.01
25%      42.50              7.84     5.83
50%      57.58             12.26     8.00
75%      70.25             18.74    11.80
max     115.83             69.09    50.32

## 5 — Merge & Clean → Final Dataset

Merge pollen, weather and air quality on `(date, city)`. The target structure is one row per city-day, with AQ adding exactly three pollutant columns: `ozone`, `nitrogen_dioxide`, `pm2_5`.

### Pollen NaN → 0: justification

The missing-value counts are **identical across all 4 cities** (e.g. birch: 378 NaN, alder: 322, grass: 316…). This is not random data loss — the CAMS European pollen model simply **does not produce forecasts for a given species outside its biological season**. Therefore, filling NaN with 0 is semantically correct: these dates correspond to periods when the species is biologically inactive and airborne concentration is effectively zero.

### Weather and AQ cleaning
- **`sunshine_duration`:** Converted from seconds → hours for interpretability.
- **Weather variables:** Linear interpolation for small gaps (≤3 days), then forward/backward fill for any remaining.
- **AQ variables:** Same interpolation/fill policy as weather after the `(date, city)` merge.

In [11]:
# ── Merge pollen + weather + air quality ────────────────────────────────────
merged = pd.merge(pollen_raw, weather_raw, on=["date", "city"], how="inner")
merged = pd.merge(merged, aq_raw[["date", "city", *AQ_VARS]], on=["date", "city"], how="left", indicator=True)

unmatched = merged[merged["_merge"] != "both"][["date", "city", "_merge"]]
assert unmatched.empty, "Every pollen-weather row must match exactly one AQ row"
merged = merged.drop(columns="_merge")

print(f"Merged shape: {merged.shape}")
print(f"Date range: {merged['date'].min().date()} → {merged['date'].max().date()}")
print(f"Cities: {merged['city'].unique().tolist()}")
print(f"AQ columns added: {AQ_VARS}")

# ── Handle missing values ───────────────────────────────────────────────────
# Pollen: fill NaN with 0 (off-season = species not modelled by CAMS → zero concentration)
merged[POLLEN_SPECIES] = merged[POLLEN_SPECIES].fillna(0)

# Weather: interpolate then forward-fill per city
for city in CITIES:
    mask = merged["city"] == city
    merged.loc[mask, WEATHER_VARS] = (
        merged.loc[mask, WEATHER_VARS]
        .interpolate(method="linear", limit=3)
        .ffill()
        .bfill()
    )

# AQ: interpolate then forward/backward fill per city (gaps expected in some regions)
for city in CITIES:
    mask = merged["city"] == city
    merged.loc[mask, AQ_VARS] = (
        merged.loc[mask, AQ_VARS]
        .interpolate(method="linear", limit=3)
        .ffill()
        .bfill()
    )

# ── Unit conversion ─────────────────────────────────────────────────────────
# sunshine_duration: seconds → hours
merged["sunshine_duration"] = merged["sunshine_duration"] / 3600.0

# Verify no NaN remain and the panel is complete.
remaining_na = merged.isna().sum().sum()
panel_check = merged.groupby("city")["date"].agg(["min", "max", "nunique"])
expected_days = len(pd.date_range(START_DATE, END_DATE, freq="D"))
assert panel_check["nunique"].eq(expected_days).all(), "Each city must have every daily row"
assert remaining_na == 0, "No NaN should remain after cleaning"

print(f"\nRemaining NaN after cleaning: {remaining_na}")
print(f"sunshine_duration range: {merged['sunshine_duration'].min():.1f}h → {merged['sunshine_duration'].max():.1f}h")
display(panel_check)
merged.info()

Merged shape: (4384, 21)
Date range: 2022-01-01 → 2024-12-31
Cities: ['Paris', 'Marseille', 'Strasbourg', 'Bordeaux']
AQ columns added: ['ozone', 'nitrogen_dioxide', 'pm2_5']

Remaining NaN after cleaning: 0
sunshine_duration range: 0.0h → 15.8h

                  min        max  nunique
city
Bordeaux   2022-01-01 2024-12-31     1096
Marseille  2022-01-01 2024-12-31     1096
Paris      2022-01-01 2024-12-31     1096
Strasbourg 2022-01-01 2024-12-31     1096

<class 'pandas.DataFrame'>
RangeIndex: 4384 entries, 0 to 4383
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   date                        4384 non-null   datetime64[s]
 1   birch_pollen                4384 non-null   float32
 2   alder_pollen                4384 non-null   float32
 3   grass_pollen                4384 non-null   float32
 4   olive_pollen                4384 non-null   float32
 5   mugwort_pollen              4384 non-null   float32
 6   ragweed_pollen              4384 non-null   float32
 7   city                        4384 non-null   str
 8   temperature_2m_mean         4384 non-null   float32
 9   temperature_2m_max          4384 non-null   float32
 10  temperature_2m_min          4384 non-null   float32
 11  precipitation_sum           4384 non-null   float32
 12  windspeed_10m_max           4384 non-null   float32
 13  sunshine_duration           4384 non-null   float32
 14  relative_humidity_2m_mean   4384 non-null   float32
 15  surface_pressure_mean       4384 non-null   float32
 16  shortwave_radiation_sum     4384 non-null   float32
 17  winddirection_10m_dominant  4384 non-null   float32
 18  ozone                       4384 non-null   float32
 19  nitrogen_dioxide            4384 non-null   float32
 20  pm2_5                       4384 non-null   float32
dtypes: datetime64[s](1), float32(19), str(1)
memory usage: 428.8 KB

In [12]:
# ── Add metadata columns ─────────────────────────────────────────────────────
merged["climate"] = merged["city"].map({c: v["climate"] for c, v in CITIES.items()})
merged["month"] = merged["date"].dt.month
merged["year"] = merged["date"].dt.year
merged["day_of_year"] = merged["date"].dt.dayofyear

# Sort for time-series consistency
merged = merged.sort_values(["city", "date"]).reset_index(drop=True)

print(f"Final dataset: {merged.shape}")
merged.head()

Final dataset: (4384, 25)

,date,birch_pollen,alder_pollen,grass_pollen,olive_pollen,mugwort_pollen,ragweed_pollen,city,temperature_2m_mean,temperature_2m_max,...,surface_pressure_mean,shortwave_radiation_sum,winddirection_10m_dominant,ozone,nitrogen_dioxide,pm2_5,climate,month,year,day_of_year
0,2022-01-01,0.0,0.0,0.0,0.0,0.0,0.0,Bordeaux,10.822917,18.502901,...,1022.688049,6.75,148.076477,18.291666,16.616667,16.583334,Oceanic,1,2022,1
1,2022-01-02,0.0,0.0,0.0,0.0,0.0,0.0,Bordeaux,11.891666,15.926955,...,1023.531433,5.61,224.043991,40.833332,12.287499,10.429167,Oceanic,1,2022,2
2,2022-01-03,0.0,0.0,0.0,0.0,0.0,0.0,Bordeaux,11.595834,15.974074,...,1020.144104,6.05,180.349854,41.250000,12.041667,8.770833,Oceanic,1,2022,3
3,2022-01-04,0.0,0.0,0.0,0.0,0.0,0.0,Bordeaux,12.393750,16.141247,...,1006.529846,3.28,245.085678,53.083332,8.537499,6.704166,Oceanic,1,2022,4
4,2022-01-05,0.0,0.0,0.0,0.0,0.0,0.0,Bordeaux,4.925000,8.000000,...,1015.843018,7.13,327.461304,40.000000,16.900000,8.933333,Oceanic,1,2022,5

## 6 — Seasonal Pollen Integral (SPIn)

### What is SPIn?

The **Seasonal Pollen Integral** (SPIn) is the standard metric in aerobiology to quantify the total pollen load for a given species during its active season (Galán et al., 2017). It is defined as:

$$\text{SPIn} = \sum_{d=d_{\text{start}}}^{d_{\text{end}}} C_d$$

where $C_d$ is the daily mean pollen concentration (grains/m³) and $[d_{\text{start}}, d_{\text{end}}]$ defines the pollen season.

### Season definition — Cumulative 5%-95% method

The pollen season boundaries are defined using the **cumulative percentage method**:
- **Season start** ($d_{\text{start}}$): first day when the cumulative sum reaches **5%** of the annual total
- **Season end** ($d_{\text{end}}$): first day when the cumulative sum reaches **95%** of the annual total

This method is preferred over fixed thresholds because:
1. It is **species-agnostic** — no need to calibrate a different threshold per species
2. It captures **90% of the annual pollen load** by construction
3. It is **robust to isolated off-season spikes** (which would trigger a fixed-threshold approach prematurely)

### Outputs computed

We compute three levels of granularity:

| Dataset | Granularity | Content |
|---------|-------------|---------|
| `spin_annual.csv` | 1 row per (city, species, year) | SPIn, season start/end/duration, peak concentration, peak date |
| `spin_monthly.csv` | 1 row per (city, species, year, month) | Monthly partial SPIn = sum of daily concentrations within each month |

Both will be useful downstream:
- **Annual SPIn** → cross-city and inter-annual comparison (research question)
- **Monthly SPIn** → intra-seasonal distribution, phenological shifts

In [13]:
# ── SPIn: Season detection + annual metrics ──────────────────────────────────

def compute_season_metrics(series, year_dates):
    """
    Compute SPIn and seasonal metrics for a single (city, species, year) group.

    Parameters
    ----------
    series : array-like — daily pollen concentrations for one year
    year_dates : array-like — corresponding dates

    Returns
    -------
    dict with: spin, season_start, season_end, season_duration_days,
               peak_concentration, peak_date
    """
    values = np.array(series, dtype=float)
    dates = np.array(year_dates)
    total = values.sum()

    # Edge case: no pollen at all this year for this species
    if total == 0:
        return {
            "spin": 0.0,
            "season_start": pd.NaT,
            "season_end": pd.NaT,
            "season_duration_days": 0,
            "peak_concentration": 0.0,
            "peak_date": pd.NaT,
        }

    # Cumulative percentage
    cumsum = np.cumsum(values)
    cum_pct = cumsum / total

    # Season start: first day >= 5% of annual total
    start_idx = np.searchsorted(cum_pct, 0.05)
    # Season end: first day >= 95% of annual total
    end_idx = np.searchsorted(cum_pct, 0.95)

    season_start = dates[start_idx]
    season_end = dates[end_idx]

    # SPIn = sum of daily concentrations within the season window
    season_values = values[start_idx : end_idx + 1]
    spin = float(season_values.sum())

    # Peak within season
    peak_idx_in_season = np.argmax(season_values)
    peak_concentration = float(season_values[peak_idx_in_season])
    peak_date = dates[start_idx + peak_idx_in_season]

    duration = (pd.Timestamp(season_end) - pd.Timestamp(season_start)).days + 1

    return {
        "spin": round(spin, 2),
        "season_start": season_start,
        "season_end": season_end,
        "season_duration_days": duration,
        "peak_concentration": round(peak_concentration, 2),
        "peak_date": peak_date,
    }


# ── Compute for all (city, species, year) combinations ───────────────────────
spin_records = []

for city in CITIES:
    city_df = merged[merged["city"] == city].sort_values("date")
    for year in sorted(merged["year"].unique()):
        year_df = city_df[city_df["year"] == year]
        for species in POLLEN_SPECIES:
            metrics = compute_season_metrics(year_df[species].values, year_df["date"].values)
            spin_records.append({
                "city": city,
                "species": species.replace("_pollen", ""),
                "year": year,
                **metrics,
            })

spin_annual = pd.DataFrame(spin_records)
print(f"SPIn annual table: {spin_annual.shape}")
print(f"Non-zero seasons: {(spin_annual['spin'] > 0).sum()} / {len(spin_annual)}")
display(spin_annual.head(12))

SPIn annual table: (72, 9)
Non-zero seasons: 72 / 72

,city,species,year,spin,season_start,season_end,season_duration_days,peak_concentration,peak_date
0,Paris,birch,2022,1597.87,2022-03-26,2022-04-26,32,145.48,2022-04-12
1,Paris,alder,2022,18.94,2022-02-13,2022-04-12,59,1.35,2022-03-02
2,Paris,grass,2022,1390.27,2022-05-17,2022-08-03,79,52.40,2022-06-19
3,Paris,olive,2022,10.63,2022-05-16,2022-06-05,21,2.62,2022-05-16
4,Paris,mugwort,2022,1428.97,2022-07-03,2022-09-19,79,63.64,2022-07-28
5,Paris,ragweed,2022,59.08,2022-08-17,2022-09-15,30,9.62,2022-09-05
6,Paris,birch,2023,1096.17,2023-03-28,2023-04-30,34,138.28,2023-04-18
7,Paris,alder,2023,101.44,2023-02-01,2023-03-29,57,17.50,2023-02-14
8,Paris,grass,2023,1329.85,2023-05-22,2023-07-23,63,55.58,2023-06-09
9,Paris,olive,2023,2.22,2023-05-04,2023-06-20,48,2.05,2023-05-04
10,Paris,mugwort,2023,915.23,2023-06-30,2023-09-25,88,36.73,2023-07-22
11,Paris,ragweed,2023,57.41,2023-08-18,2023-09-16,30,6.35,2023-09-08

In [14]:
# ── SPIn: Monthly partial integral ────────────────────────────────────────────
# Monthly SPIn = sum of daily concentrations within each calendar month.
# This is NOT restricted to the season window — it captures the full annual
# distribution so we can observe when pollen load accumulates month by month.

spin_monthly_records = []

for city in CITIES:
    city_df = merged[merged["city"] == city].sort_values("date")
    for year in sorted(merged["year"].unique()):
        year_df = city_df[city_df["year"] == year]
        for species in POLLEN_SPECIES:
            species_name = species.replace("_pollen", "")
            monthly_sums = year_df.groupby("month")[species].sum()
            for month, monthly_spin in monthly_sums.items():
                spin_monthly_records.append({
                    "city": city,
                    "species": species_name,
                    "year": year,
                    "month": month,
                    "spin_monthly": round(float(monthly_spin), 2),
                })

spin_monthly = pd.DataFrame(spin_monthly_records)
print(f"SPIn monthly table: {spin_monthly.shape}")
display(spin_monthly[spin_monthly["spin_monthly"] > 0].head(10))

SPIn monthly table: (864, 5)

     city species  year  month  spin_monthly
2   Paris   birch  2022      3        544.62
3   Paris   birch  2022      4       1192.00
4   Paris   birch  2022      5         10.42
5   Paris   birch  2022      6          1.42
12  Paris   alder  2022      1          0.12
13  Paris   alder  2022      2          7.25
14  Paris   alder  2022      3         10.79
15  Paris   alder  2022      4          1.77
16  Paris   alder  2022      5          0.32
26  Paris   grass  2022      3          0.16

In [15]:
# ── Quick validation: SPIn annual vs monthly consistency ──────────────────────
# The annual SPIn (computed on the 5%-95% season window) should be ≤ the sum of
# all monthly SPIn (which covers the full year). Let's verify.

check = spin_monthly.groupby(["city", "species", "year"])["spin_monthly"].sum().reset_index()
check.columns = ["city", "species", "year", "full_year_sum"]
check = check.merge(spin_annual[["city", "species", "year", "spin"]], on=["city", "species", "year"])
check["ratio_season_to_full"] = (check["spin"] / check["full_year_sum"].replace(0, np.nan)).round(3)

print("SPIn season (5%-95%) vs full year sum — should be ~0.90 by construction:")
print(f"  Mean ratio: {check['ratio_season_to_full'].mean():.3f}")
print(f"  Min ratio:  {check['ratio_season_to_full'].min():.3f}")
print(f"  Max ratio:  {check['ratio_season_to_full'].max():.3f}")

SPIn season (5%-95%) vs full year sum — should be ~0.90 by construction:
  Mean ratio: 0.921
  Min ratio:  0.901
  Max ratio:  0.993

## 7 — Save Processed Data

We save four types of datasets:
- **Long format** (`pollen_weather_merged.csv`): one row per (date, city) — daily time series
- **Per-city CSVs** (`pollen_weather_{city}.csv`): one file per city — for individual TS modelling
- **SPIn annual** (`spin_annual.csv`): one row per (city, species, year) — seasonal metrics
- **SPIn monthly** (`spin_monthly.csv`): one row per (city, species, year, month) — monthly partial integral

In [16]:
# ── Save processed data ──────────────────────────────────────────────────────
# Full merged dataset. `pollen_weather_merged.csv` remains the canonical model input and now includes AQ columns;
# `pollen_weather_aq_merged.csv` is an explicit AQ-enriched alias used by NB05.
merged_path = os.path.join(DATA_PROC, "pollen_weather_merged.csv")
merged.to_csv(merged_path, index=False)
print(f"Saved: {merged_path} ({merged.shape})")

merged_aq_path = os.path.join(DATA_PROC, "pollen_weather_aq_merged.csv")
merged.to_csv(merged_aq_path, index=False)
print(f"Saved: {merged_aq_path} ({merged.shape})")

# Per-city files
for city in CITIES:
    city_df = merged[merged["city"] == city].copy()
    city_path = os.path.join(DATA_PROC, f"pollen_weather_{city.lower()}.csv")
    city_df.to_csv(city_path, index=False)
    print(f"Saved: {city_path} ({city_df.shape})")

# SPIn datasets
spin_annual_path = os.path.join(DATA_PROC, "spin_annual.csv")
spin_annual.to_csv(spin_annual_path, index=False)
print(f"Saved: {spin_annual_path} ({spin_annual.shape})")

spin_monthly_path = os.path.join(DATA_PROC, "spin_monthly.csv")
spin_monthly.to_csv(spin_monthly_path, index=False)
print(f"Saved: {spin_monthly_path} ({spin_monthly.shape})")

Saved: ../Data/processed/pollen_weather_merged.csv ((4384, 25))
Saved: ../Data/processed/pollen_weather_aq_merged.csv ((4384, 25))

Saved: ../Data/processed/pollen_weather_paris.csv ((1096, 25))
Saved: ../Data/processed/pollen_weather_marseille.csv ((1096, 25))
Saved: ../Data/processed/pollen_weather_strasbourg.csv ((1096, 25))
Saved: ../Data/processed/pollen_weather_bordeaux.csv ((1096, 25))
Saved: ../Data/processed/spin_annual.csv ((72, 9))
Saved: ../Data/processed/spin_monthly.csv ((864, 5))

## 8 — Quick Visual Sanity Check

Plot one pollen species (grass) across all 4 cities to confirm data looks reasonable.

In [17]:
# ── Quick sanity plot ────────────────────────────────────────────────────────
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

fig, axes = plt.subplots(4, 1, figsize=(14, 10), sharex=True)
fig.suptitle("Grass Pollen — Daily Mean Concentration (grains/m³)", fontsize=14, fontweight="bold")

for ax, city in zip(axes, CITIES):
    city_df = merged[merged["city"] == city]
    ax.plot(city_df["date"], city_df["grass_pollen"], linewidth=0.8, color="forestgreen")
    ax.set_ylabel("grains/m³")
    ax.set_title(city, fontsize=11, loc="left")
    ax.grid(True, alpha=0.3)

axes[-1].xaxis.set_major_locator(mdates.MonthLocator(interval=3))
axes[-1].xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))
plt.xticks(rotation=45)
plt.tight_layout()
fig.savefig(os.path.join("..", "figures", "00_grass_pollen_sanity_check.png"), dpi=300, bbox_inches="tight")
plt.show()
print("Sanity check plot saved.")

Sanity check plot saved.

---

## Summary

| Item | Detail |
|------|--------|
| **Cities** | Paris, Marseille, Strasbourg, Bordeaux |
| **Period** | 2022-01-01 → 2024-12-31 (1096 days/city) |
| **Pollen species** | birch, alder, grass, olive, mugwort, ragweed |
| **Weather variables** | temp mean/max/min, precipitation, wind speed, sunshine (h), relative humidity, pressure, radiation, wind direction |
| **AQ variables** | ozone, nitrogen_dioxide, pm2_5 — hourly API data resampled to daily mean |
| **Panel key** | one row per `(date, city)` |
| **SPIn method** | Cumulative 5%–95% season definition (Galán et al., 2017) |
| **Raw files** | `Data/raw/pollen_raw.csv`, `Data/raw/weather_raw.csv`, `Data/raw/aq_raw.csv` |
| **Processed files** | `pollen_weather_merged.csv`, `pollen_weather_aq_merged.csv`, per-city CSVs, `spin_annual.csv`, `spin_monthly.csv` |
| **Cleaning** | Pollen NaN → 0 (off-season, structural), sunshine sec→h, weather/AQ interpolated per city |